PATIENT MONITORING SYSTEM WITH NUMPY  

The project implements a simple patient monitoring system using Numpy. Synthetic data was generated for 4 patients over 3 days, with measurement taken twice daily(morning and evening). Each patient record contains:
1. Heart Rate (bpm)
2. Systolic Blood Pressure (mmHg)
3. Diastolic Blood Pressure (mmHg)
4. Temperature
The project demonstrates how Numpy arrays can be used to structure, manipulate and analyze multidimensional healthcare data for insights that support public health decision making.

What I did

1. Synthetic Data Generation:
   
Created a (4, 3, 2, 4) Numpy array:
        Axis 0 - Patients (4);
        Axis 1 - Days (3);
        Axis 2 - Time of Day (Morning/Evening);
        Axis 3 - Vital signs (HR, SBP, DBP, Temp);
   
Generated values within medical ranges:
       1. Heart Rate: 60- 100 bpm
       2. SBP: 90 - 120 mmHg
       3. DBP: 60- 80 mmHg
       4. Temperature: 36- 39 degree celsius
        
2. Data Analysis Tasks
       1. Extracted- specific and day-specific vital signs
       2. Isolated values for key indicators (e.g., evening HR, all temperatures for a patient)
       3. Detected abnormal readings (e.g., fever >37.5)
       4. Checked for critical events (SBP > 140mmHg)
       5. Computed averages(e.g., average HR per patient, mean SBP across hospital)
       6. Found maximum values(e.g., max temperature per day for a patient)
       7. Sorted patient by average heart rate
       8. Created new arrays for focused monitoring (e.g., only HR and Temp)

In [1]:
import numpy as np

# Generate synthetic data
# Shape: (patients=4, days=3, times=2, vitals=4)
np.random.seed(42)

data = np.zeros((4, 3, 2, 4))

# Heart Rate (60- 100 bpm)
data[..., 0] = np.random.randint(60, 101, size=(4, 3, 2))

# Systolic BP (90- 120 mmHg)
data[..., 1] = np.random.randint(90, 121, size=(4, 3, 2))

# Diastolic BP (60- 80 mmHg)
data[..., 2] = np.random.randint(60, 81, size=(4, 3, 2))

# Temperature (36-39 degree celsius)
data[..., 3] = np.random.uniform(36, 39, size=(4, 3, 2))

#-----------------------------------------------------
# Extract all vital signs for Patient 0 on Day 3
patient0_day3 = data[0, 2, :, :]
print("Patient 0 - Day 3:\n", patient0_day3)

# Extract all Temperature values for Patient 3 across all days
patient3_temp = data[3, :, :, 3]
print("\nPatient 3 Temperature:\n", patient3_temp)

# Extract the Evening Heart rate for all patients on day 2
evening_hr_day2 = data[:, 1, 1, 0]
print("\nEvening HR (Day 2):\n", evening_hr_day2)

# Extract the data for patient 1, 2 and 4 only
patients_1_2_4 = data[[0, 1, 3], :, :, :]
print("\nPatients 1, 2, 4 data shape:", patients_1_2_4.shape)

# Extract the data for Days 2, 3 for Patient 2
patient2_days23 = data[1, 1:3, :, :]
print("\nPatient 2 - Days 2 & 3:\n", patient2_days23)

# Find all readings where Temperature > 37.5 degree celsius
high_temp_indices = np.argwhere(data[..., 3] > 37.5)
print("\nReadings where Temp > 37.5:\n", high_temp_indices)

# Identify patients who has systolic BP > 140
bp_over_140 = np.any(data[..., 1]>140, axis=(1, 2))
patients_bp_high = np.where(bp_over_140)[0]
print("\nPatients with SBP > 140:\n", patients_bp_high)

# Compute average heart rate per patients across all days
avg_hr_per_patient = np.mean(data[..., 0], axis=(1,2))
print("\nAverage HR per patient:\n", avg_hr_per_patient)

# Find maximum temperature per day for patient 3
max_temp_patient3 = np.max(data[2, :, :, 3], axis=1)
print("\nMax Temp per day (Patient 3):\n", max_temp_patient3)

# Compute the overall mean SBP across all patients
mean_sbp = np.mean(data[..., 1])
print("\nOverall mean SBP:\n", mean_sbp)

# Create new array stacking heart rate and temperature only
hr_temp = data[..., [0, 3]]
print("\nHeart Rate + Temperature shape:", hr_temp.shape)

# Short average heart rate of all patients (ascending)
sorted_avg_hr = np.sort(avg_hr_per_patient)
print("\nSorted Avg HR:\n", sorted_avg_hr)

Patient 0 - Day 3:
 [[ 80.         114.          68.          36.55456337]
 [ 98.         106.          66.          38.90875388]]

Patient 3 Temperature:
 [[37.07025998 36.84280353]
 [37.62808825 36.42277267]
 [38.40659094 36.22365193]]

Evening HR (Day 2):
 [67. 70. 81. 80.]

Patients 1, 2, 4 data shape: (3, 3, 2, 4)

Patient 2 - Days 2 & 3:
 [[[ 70.         120.          73.          38.68448205]
  [ 70.          99.          77.          37.79369994]]

 [[ 83.         117.          68.          38.76562271]
  [ 95.         117.          80.          36.26547751]]]

Readings where Temp > 37.5:
 [[0 0 0]
 [0 1 0]
 [0 1 1]
 [0 2 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]
 [1 2 0]
 [2 2 1]
 [3 1 0]
 [3 2 0]]

Patients with SBP > 140:
 []

Average HR per patient:
 [84.16666667 79.66666667 78.16666667 81.66666667]

Max Temp per day (Patient 3):
 [36.58794859 37.16603187 38.48621253]

Overall mean SBP:
 110.66666666666667

Heart Rate + Temperature shape: (4, 3, 2, 2)

Sorted Avg HR:
 [78.1666